AUGMENTATION: True  # less data set then one image is made into no of images by changing colours, etc
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model, from their research paper
BATCH_SIZE: 16
INCLUDE_TOP: False  # only convolution layers is considered if TRUE ANN layer is also added
EPOCHS: 1
CLASSES: 2  # dog,cat
WEIGHTS: imagenet  # it has 1000 no of classes it has wide variety of weights
LEARNING_RATE: 0.01

# imagenet : it is a dataset, in competetion of ddataset,people have trained on various weights,so model trained on those weights 